extends Node

var score = 0

@onready var label: Label = $Label
@onready var onscreen_label: Label = $"../CanvasLayer/Label2"


func add_point():
	score += 1
	label.text = "Coins: " + str(score)
	onscreen_label.text = "Collected coins: " + str(score) + "🟡"

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass
